site_name: Lynx CRM - Docs
site_description: 
copyright: Lynx CRM
site_url: https://docs.lynx.vn
site_author: Lynx

theme: readthedocs
theme_dir: xf2
extra_css: [extra.css]
    
repo_name: Github
repo_url: https://github.com/mynukeviet/lynx-docs

markdown_extensions:
    - toc:
        permalink: "#"
        
pages:
- Bắt đầu: index.md
- Modules:
    - Thông báo: modules/notification.md
    - Hóa đơn: modules/invoice.md