site_name: Lynx CRM - Docs
site_description: 
site_url: https://docs.lynx.vn
site_author: TDFOSS.,LTD

theme: readthedocs
theme_dir: themes/xf2
extra_css: [extra.css]
    
repo_name: Github
repo_url: https://github.com/mynukeviet/lynx-docs

markdown_extensions:
    - admonition
    - toc:
        permalink: "#"
        
pages:
- Bắt đầu: index.md
- Lịch: modules/calendar.md
- Thông báo: modules/notification.md
- Nhân sự: modules/workforce.md
- Khách hàng: modules/customer.md
- Dự án: modules/projects.md
- Hóa đơn: modules/invoice.md
- Email: modules/email.md
- Khác: modules/other.md
